Bh 7
MurFlex/BotHub pull request #14
Opened 2024-10-03 16:32 UTC by CandyDog13

2024-10-09 18:24 UTC, MurFlex requested changes

2024-10-09 18:24 UTC, MurFlex commented on client/src/pages/Home/index.tsx
> +import { IItems } from "../../components/DropdownMenu/DropdownMenu.props";
IItem

2024-10-09 18:24 UTC, MurFlex commented on client/src/components/DropdownMenu/MenuItem/MenuItem.tsx
> +            <NavLink to={item.value} className={styles.nivLink}>{item.label}</NavLink>
navLink (но лучше просто link т.к. стили модульные и бэм тут не так важен)

2024-10-09 18:24 UTC, MurFlex commented on client/src/components/DropdownMenu/MenuItem/MenuItem.module.scss
> +.nivLink {
nav

2024-10-09 18:24 UTC, MurFlex commented on client/src/components/DropdownMenu/DropdownMenu.tsx
> +            <MenuItem item={item}></MenuItem>
Одиночный тэг

2024-10-09 18:24 UTC, MurFlex commented on client/src/components/DropdownMenu/DropdownMenu.module.scss
> +  border: $border_accent;
Рамка тут 1 пиксель

2024-10-09 18:24 UTC, MurFlex commented on client/src/components/DropdownMenu/DropdownMenu.tsx
> +      <nav className={styles.dropdown__menu}>
Nav лучше сделать в хедере как набор из дропдаунов
Будет 
nav > ul (список из дропдаунов) и в ul засунуть много li с DropdownMenu. Надо сделать лейбл в спане (параграф не очень в этом кейсе, все-таки это больше просто висящий текст, а не смысловой отрезок) и при наведении на лейбл будет появляться ul, который будет обернут в див. у дива сделать паддинг, а ul будет иметь те стили, которые уже сделаны. Тогда не будет постоянно висящего паддинга, он появится когда наведешь на спан
![image](https://github.com/user-attachments/assets/96a2bfe4-4a92-49ee-a4a1-2388a6c5d594)

2024-10-10 08:31 UTC, CandyDog13 commented on client/src/components/DropdownMenu/DropdownMenu.tsx
> +      <nav className={styles.dropdown__menu}>
Не понял как в таком случае уйдет паддинг, но я пофиксил по другому постоянно висящий паддинг

2024-10-13 11:09 UTC, MurFlex approved these changes

2024-10-13 12:54 UTC, merged